briefcase/urls.py
from django.urls import path

from .views import StudyMain, ExperienceMain, curriculum, studydelete, experiencedelete

app_name="briefcase"

urlpatterns = [
    path('studies/', StudyMain.as_view(), name='studies'),
    path('studies/<int:id>', StudyMain.as_view(), name='study'),
    path('experiences/', ExperienceMain.as_view(), name='experiences'),
    path('experiences/<int:id>', ExperienceMain.as_view(), name='exp'),
    path('curriculum/', curriculum, name='curriculum'),
    path('curriculum/<int:id>', curriculum, name='curriculumparam'),
    path('deletestudy/<int:id>', studydelete, name='deletestudy'),
    path('deleteexperience/<int:id>', experiencedelete, name='deleteexperience'),
]

home/urls.py
"""Rutas para home"""
from django.urls import path

from .views import HomeView, curriculums

app_name = "home"

urlpatterns = [
    path('', HomeView.as_view(template_name='home/home.html'), name='home'),
    path('curriculums/', curriculums, name = "listcurriculums")
]

portF/urls.py
from django.contrib import admin

#para trabajar con media
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import login_redirect

urlpatterns = [
    path('', login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #se agregan urls de
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('briefcase/', include('briefcase.urls', namespace='briefcase')), 
    # path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    # path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

briefcase/models.py
from django.db import models
from django.contrib.auth.models import User

class Studies(models.Model):
    """modelo para representar estudios"""
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    gradedate = models.DateField()
    school = models.CharField(max_length=50)
    show = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Estudio'
        verbose_name_plural = 'Estudios'

    def __str__(self):
        return self.name

class Experience(models.Model):
    """modelo para representar experiencia laboral"""
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    appointment = models.CharField(max_length=100)
    startdate = models.DateField()
    enddate = models.DateField()
    company = models.CharField(max_length=50)
    show = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Experiencia'
        verbose_name_plural = 'Experiencia'

    def __str__(self):
        return self.appointment

briefcase/forms.py
from django import forms

from .models import Studies, Experience

class AddStudyForm(forms.ModelForm):
    """formulario para mostrar estudios"""
    show = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox','class':'filled-in','checked':'checked'}))
    class Meta:
        model = Studies
        fields = (
            'name',
            'gradedate',
            'school',
            'show',
        )

class AddExperienceForm(forms.ModelForm):
    """formulario para agregar una nueva "experiencia"""
    class Meta:
        model = Experience
        fields = (
            'appointment',
            'startdate',
            'enddate',
            'company',
            'show',
        )
            

briefcase/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from .models import Studies, Experience
from accounts.models import UserProfile
from django.contrib.auth.models import User

from .forms import AddStudyForm, AddExperienceForm

# Create your views here.
class StudyMain(TemplateView):
    template_name = 'studies/studies.html'

# metodo get para traer el formulario
    def get(self, request, id=None):
        if id:
            studies = Studies.objects.get(id=id)
            form = AddStudyForm(instance=studies)
        else:
            form = AddStudyForm()
        studies = Studies.objects.filter(user=request.user)
        args = {
            'form':form,
            'studies':studies,
            }
        return render(request, self.template_name, args)
    
# metodo post para guardar en el modelo
    def post(self, request, id=None):
        if id:
            form = AddStudyForm(request.POST)
            if form.is_valid():
                studyE = form.save(commit=False)
                studyE.id=id
                studyE.user=request.user
                studyE.save()
            return redirect('briefcase:studies')
        form = AddStudyForm(request.POST)
        if form.is_valid():
        # evito que haga el commit de save()
            study = form.save(commit=False)
        # agrego el campo de usuario almacenado en el request
            study.user = request.user
        # save :)
            study.save()
        # vacio el formulario
            form = AddStudyForm()
        # redirecciono
            return redirect('briefcase:studies')
        
        args = {'form':form}
        return render(request, self.template_name, args)

class ExperienceMain(TemplateView):
    template_name = 'experience/experience.html'
    
    def get(self, request, id=None):
        if id:
            exp = Experience.objects.get(id=id)
            form = AddExperienceForm(instance=exp)
        else:
            form = AddExperienceForm()
        exp = Experience.objects.filter(user=request.user)
        args = {
            'form':form, 'exp':exp
            }
        return render(request, self.template_name, args)

    def post(self, request, id=None):
        if id:
            form = AddExperienceForm(request.POST)
            if form.is_valid():
                expe = form.save(commit=False)
                expe.id=id
                expe.user=request.user
                expe.save()
            return redirect('briefcase:experiences')
        form = AddExperienceForm(request.POST)
        if form.is_valid():
            # detener que guarde el objeto para agregarle un campo automatico
            experience = form.save(commit=False)
            experience.user = request.user
            experience.save()
            form = AddExperienceForm()
            return redirect('briefcase:experiences')
        args = {'form':form}
        return render(request, self.template_name, args)

def curriculum(request, id=None):
    if id:
        user = User.objects.get(id=id)
        params = UserProfile.objects.get(user=id)
        studies = Studies.objects.filter(user=id)
        experience = Experience.objects.filter(user=id)
        args = {
            'user':user,
            'params':params,
            'studies':studies,
            'experience':experience,
        }
        return render(request, 'curriculum/param.html', args)
    params = UserProfile.objects.get(user=request.user)
    studies = Studies.objects.filter(user=request.user)
    experience = Experience.objects.filter(user=request.user)
    args = {
        'params':params,
        'studies':studies,
        'experience':experience,
    }
    return render(request, 'curriculum/index.html', args)

def studydelete(request, id=None):
    Studies.objects.get(id=id).delete()
    return redirect('briefcase:studies')

def experiencedelete(reqest, id=None):
    Experience.objects.get(id=id).delete()
    return redirect('briefcase:experiences')

briefcase/templates/studies/studies.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>Studies</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                    <h1>Studies</h1>
                <div class="row">
                    <div class="col s12">
                        <form method="POST">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button class="btn" type="submit">Guardar</button>
                        </form>
                    </div>
                    <div class="col s12">                       
                        <div class="row">
                            {% for study in studies %} 
                            <div class="col s4">
                                <div class="card blue-grey darken-1">
                                    <div class="card-content white-text">
                                        <span class="card-title">{{study.name}}</span>
                                        <ul>
                                            <li>{{study.school}}</li>
                                            <li>{{study.gradedate}}</li>
                                        </ul>
                                    </div>
                                    <div class="card-action">
                                        <a href="{% url 'briefcase:study' id=study.id %}">Editar</a>
                                        <a href="{% url 'briefcase:deletestudy' id=study.id %}">Eliminar</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>              
                    </div>
                </div>              
            </div>
        </section>
    {% endblock %} 