accounts/urls.py
"""Urls accounts"""
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import register, profile, edit, changepassword, info

# rutas para accounts

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('edit/', edit, name='edit'),
    path('info', info, name='info'),
    path('changepassword/', changepassword, name='changepassword'),    
    # path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    # path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'), 
    # path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'), 
    # path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

home/urls.py
"""Rutas para home"""
from django.urls import path

from .views import HomeView, curriculums

app_name = "home"

urlpatterns = [
    path('', HomeView.as_view(template_name='home/home.html'), name='home'),
    path('curriculums/', curriculums, name = "listcurriculums")
]

portF/urls.py
from django.contrib import admin

#para trabajar con media
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import login_redirect

urlpatterns = [
    path('', login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #se agregan urls de
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('briefcase/', include('briefcase.urls', namespace='briefcase')), 
    # path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    # path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
# signal para crear perfil de usuario una vez creao el usuario
from django.db.models.signals import post_save
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    documenttype = models.CharField(max_length=50)
    document = models.CharField(max_length=50) 
    civilstatus = models.CharField(max_length=50) 
    ethnicgroup = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    avatar = models.ImageField(upload_to='avatars', blank=True)

    class Meta:
        verbose_name = 'Perfil usuario'
        verbose_name_plural = 'Perfiles de usuario'

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    #si el usuario es creado..
    if kwargs['created']:
        #crea instancia de perfildeusuario
        UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import UserProfile

#cre formulariode registro personalizado HEREDANDO DE USERCREATIONFORM
class RegistrationForm(UserCreationForm):
    #los campos de más que quiero agregar:
    email = forms.EmailField(required=True)

    # Defino parametros meta
    class Meta:
        model = User
        fields = [
            'email',
            'username',
            'password1',
            'password2',
        ]
    
    #metodo save(), para gaurdar SELF o mejor dicho para gaurdar LOSDATOSDELFORMULARIO en el modelo
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        if commit:
            user.save()
        return user

class EditProfileform(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
        ] 

class InfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [            
            'documenttype',
            'document',
            'civilstatus',
            'ethnicgroup',
            'genre',
            'avatar',
        ]

accounts/views.py
"""Metodos para cuenta de usuario"""
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
#modulo para evitar que se cere sesion al cambiar contraseña
from django.contrib.auth import update_session_auth_hash
#decorador para validar sesion
from django.contrib.auth.decorators import login_required

from .forms import RegistrationForm, EditProfileform, InfoForm

# Create your views here.

def register(request):
    """metodo de registro  usuario"""
    if request.method == 'POST':
        form = RegistrationForm(request.POST) 
        if form.is_valid():
            form.save()
        return redirect('home:home') 
    else:
        form = RegistrationForm()
    return render(request, 'accounts/register.html', {'form':form})

@login_required
def profile(request):
    """metodo para acceder a la informacion de perfil del usuario"""
    args = {'user':request.user}
    return render(request, 'accounts/profile.html', args)

@login_required
def info(request):
    """metodo para editar y mostrar informacion de usuario"""
    if request.method == 'POST':
        form = InfoForm(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = InfoForm(instance=request.user.userprofile)
        args = {'form':form}
    return render(request, 'accounts/info.html', args)

@login_required
def edit(request):
    """metodo para editar y mostrar informaciion personal de usuario"""
    if request.method == 'POST':
        form = EditProfileform(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = EditProfileform(instance=request.user)
        args = {'form':form}
    return render(request, 'accounts/edit.html', args)

@login_required
def changepassword(request):
    """metodo para cambiar contraseña"""
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:profile')
        else:
            return redirect('accounts:changepassword')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form':form}
    return render(request, 'accounts/changepassword.html', args)

accounts/templates/accounts/changepassword.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>Change Password</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                <h1>Change Password</h1>
                <section class="section">                    
                    <div class="row">
                        <form method="POST" class="col s12">
                            {% csrf_token %}
                            {{form.as_p}}
                            <div>
                                <button class="btn" type="submit">Actualizar</button>
                            </div>
                        </form>
                    </div>            
                </section>
            </div>
        </section>
    {% endblock %}  

accounts/templates/accounts/edit.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>Profile</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                <h1>Profile {{ user.username }} </h1>
                <section class="section">                    
                    <div class="row">
                        <form method="POST" class="col s12">
                            {% csrf_token %}
                            {{form.as_p}}
                            <div>
                                <button class="btn" type="submit">Actualizar</button>
                            </div>
                        </form>
                    </div>            
                </section>
            </div>
        </section>
    {% endblock %}  

accounts/templates/accounts/info.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>Info</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                <h1>Info {{ user }} </h1>
                <section class="section">                    
                    <div class="row">
                        <form method="POST" enctype="multipart/form-data" class="col s12">
                            {% csrf_token %}
                            <div class="row valign-wrapper">                                  
                                <div class="col s8">
                                        {{form.as_p}}
                                </div>    
                                <div class="col s4">
                                    {% if user.userprofile.avatar %}                           
                                    <a href="{{ user.userprofile.avatar.url }}"><img class="responsive-img  valign-wrapper" src="{{ user.userprofile.avatar.url }}" alt="nada"></a>
                                    {% endif %}
                                </div>                        
                            </div> 
                            <div>
                                <button class="btn" type="submit">Guardar</button>
                                <a href="{% url 'accounts:profile' %}" class="btn">Regresar</a>
                            </div>
                        </form>                                                
                    </div>            
                </section>
            </div>
        </section>
    {% endblock %}  

accounts/templates/accounts/login.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>Login</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                <h1 id="login">Login</h1>
                <p>wellcome set you'r data please</p>
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn" type="submit">Log In</button>
                    <br>
                    <section class="section">
                            <a href="/reset-password">Olvidé mi contraseña</a>
                    </section>
                </form>
            </div>
        </section>
    {% endblock %}  
        

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>LogOut</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                <h1>Log Out</h1>
                You have logged out
            </div>
        </section>
    {% endblock %}  

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>Profile</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                <h1>Profile {{ user }} </h1>
                <section class="section">                    
                    <div class="row">
                        <form method="POST" class="col s12">
                            <div class="row">
                                <div class="col s4 ">
                                        {% if user.userprofile.avatar %}                       
                                        <a href="{{ user.userprofile.avatar.url }}"><img class="responsive-img" src="{{ user.userprofile.avatar.url }}" alt="nada"></a>
                                        {% endif %}
                                </div>
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">perm_identity</i>
                                    <label>{{ user.username }}</label>
                                </div>
                                <!-- <div class="input-field col s12">
                                    <i class="material-icons prefix">account_circle</i>
                                    <label>{{user.first_name}}</label>
                                </div>                                 -->
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">local_post_office</i>
                                    <label>{{ user.email }}</label>
                                </div>
                            </div> 
                            <br>
                            <section class="section">
                                <div><a href="/account/changepassword">Cambiar contraseña</a></div>
                            </section>
                            <br>
                            <a href="{% url 'accounts:edit' %}" class="btn">Editar</a>
                        </form>                        
                    </div>            
                </section>                
            </div>
        </section>
    {% endblock %}  

accounts/templates/accounts/register.html
{% extends 'base.html' %}

    {% block head %}         
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
        <title>Register</title>
    {% endblock %}
    
    {% block body %}
        <section class="section">
            <div class="container">
                <h1>Register</h1>
                <p>wellcome Hope you enjoy</p>
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn" type="submit">Log In</button>
                </form>
            </div>
        </section>
    {% endblock %}  