accounts/urls.py
"""Urls accounts"""
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import register, profile, edit, changepassword, info

# rutas para accounts

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('edit/', edit, name='edit'),
    path('info', info, name='info'),
    path('changepassword/', changepassword, name='changepassword'),    
    # path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    # path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'), 
    # path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'), 
    # path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

briefcase/urls.py
from django.urls import path

from .views import StudyMain, ExperienceMain, curriculum, studydelete, experiencedelete

app_name="briefcase"

urlpatterns = [
    path('studies/', StudyMain.as_view(), name='studies'),
    path('studies/<int:id>', StudyMain.as_view(), name='study'),
    path('experiences/', ExperienceMain.as_view(), name='experiences'),
    path('experiences/<int:id>', ExperienceMain.as_view(), name='exp'),
    path('curriculum/', curriculum, name='curriculum'),
    path('curriculum/<int:id>', curriculum, name='curriculumparam'),
    path('deletestudy/<int:id>', studydelete, name='deletestudy'),
    path('deleteexperience/<int:id>', experiencedelete, name='deleteexperience'),
]

home/urls.py
"""Rutas para home"""
from django.urls import path

from .views import HomeView, curriculums

app_name = "home"

urlpatterns = [
    path('', HomeView.as_view(template_name='home/home.html'), name='home'),
    path('curriculums/', curriculums, name = "listcurriculums")
]

portF/urls.py
from django.contrib import admin

#para trabajar con media
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .views import login_redirect

urlpatterns = [
    path('', login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    #se agregan urls de
    path('account/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('briefcase/', include('briefcase.urls', namespace='briefcase')), 
    # path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    # path('reset-password/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- materialize -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    {% block head %}
    <title>Base</title>
    {% endblock %}
</head>
<body>
    
    {% include 'navbar.html' %}
    
    {% block body %}
    {% endblock %}
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>   
    <script src="{% static 'js/js.js' %}" ></script>
</body>
</html>

templates/navbar.html
{% load static %}
<section>
        <nav class="blue accent-4">
            <div class="container">
                <div class="nav-wrapper">
                    <div class="row">
                        <div class="col s4">
                            <ul>
                                <li><a href="{% url 'home:home' %}" class=" Left">PTF</a></li>
                                <li><a class="hide-on-med-and-down" href="{% url 'home:listcurriculums' %}">Curriculums</a></li>
                            </ul>                           
                        </div>                 
                        <div class="col s8">
                            <a href="#" data-target="mobile-demo" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
                                <ul class="right hide-on-med-and-down">
                                {% if request.user.is_authenticated %}
                                <!-- Dropdown Trigger -->                                
                                <li><a href="{% url 'briefcase:curriculum' %}">Mi Curriculum</a></li>  
                                <li><a class='dropdown-trigger' href='#' data-target='acc'>{{user.username}}</a></li>                             
                                <li><a href="/account/logout">LogOut</a></li>  
                                {% else %}                                             
                                <li><a class='dropdown-trigger' href='#' data-target='act'>Account</a></li>
                                {% endif %}
                            </ul>
                        </div>                        
                    </div>
                </div>
            </div>   
            <!-- Dropdown Structure -->
            <ul id='act' class='dropdown-content'>
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
            </ul>      
            <!-- Dropdown Structure -->
            <ul id='acc' class='dropdown-content'>
                <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                <li><a href="{% url 'accounts:info' %}">User Data</a></li>
                <li><a href="{% url 'briefcase:studies' %}">Studies</a></li>
                <li><a href="{% url 'briefcase:experiences' %}">Experience</a></li>
            </ul> 
            <!-- Dropdown Structure -->
            <ul id='acc1' class='dropdown-content'>
                <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                <li><a href="{% url 'accounts:info' %}">User Data</a></li>
                <li><a href="{% url 'briefcase:studies' %}">Studies</a></li>
                <li><a href="{% url 'briefcase:experiences' %}">Sxperience</a></li>
            </ul>      
            <ul id='act1' class='dropdown-content'>
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
            </ul>                   
        </nav>

        <ul class="sidenav center" id="mobile-demo">
            <section class="section">
                <div class="container">
                    <div class="row">
                        <a href="{% url 'home:home' %}">
                            <div class="col s6 offset-s3">
                                <img src="{% static 'assets/logic.jpg' %}" alt="" class="circle responsive-img">
                                <h5 class=center>Portfolio</h5>
                            </div>
                        </a>
                    </div>
                </div>
            </section>
            <hr>            
            <li><a href="{% url 'home:listcurriculums' %}">Curriculum's</a></li>
            {% if request.user.is_authenticated %}
            <hr>             
            <li><a href="{% url 'briefcase:curriculum' %}">Mi Curriculum</a></li>
            <li><a class='dropdown-trigger' href="#" data-target='acc1'>Profile</a></li>                   
            <li><a class='red btn' href="/account/logout">Log Out</a></li>
            {% else %}
            <!-- Dropdown Trigger -->
            <hr>
            <a class='dropdown-trigger btn' href='#' data-target='act1'>Profile</a>
            {% endif %}
        </ul>
    </section>  
    